[build]
  publish = "dist"
  command = "npm run build"

# Single SPA fallback; assets will match fixed names, so no need for exemptions
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
